variables: !include /storage/agrp/dreyet/GNtau/GNtau/umami/tau-variables.yaml

qcd: &qcd
  name: qcd
  pattern: "qcd/jet_samp*.h5"

tau: &tau
  name: tau
  pattern: "tau/tau_samp*.h5"

global_cuts:
  train:
    - [eventNumber, "%10<=", 6]
  val:
    - [eventNumber, "%10==", 7]
  test:
    - [eventNumber, "%10>=", 7]

lowpt: &lowpt
  name: lowpt
  cuts:
    []
    # - [pt, ">=", 20_000]
    # - [pt, "<=", 150_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *qcd
    flavours: [ujets]
    num_jets: 48_000_000
    # num_jets_val: 7_400_000
    num_jets_test: 14_400_000

  - region:
      <<: *lowpt
    sample:
      <<: *tau
    flavours: [bjets]
    num_jets: 10_000_000
    # num_jets_val: 1_600_000
    num_jets_test: 3_000_000

resampling:
  target: bjets
  method: countup
  sampling_fraction: 1.0
  variables:
    pt:
      bins: [[5_000, 3_000_000, 50]]
    absEta:
      bins: [[0, 2.5, 20]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 5_000_000
  num_jets_estimate: 5_000_000
  base_dir: /storage/agrp/dreyet/GNtau/samples/v04/
  merge_test_samples: True
